import { useState } from "react";
import type { FormEvent } from "react";
import { FormActions } from "../forms/FormActions";
import { ModalForm } from "../forms/ModalForm";
import type { WorkSession, WorkSessionInput } from "../../types/productivity";
import { toDateKey } from "../../utils/date";

type Props={session:WorkSession|null;onClose:()=>void;onSave:(input:WorkSessionInput)=>Promise<void>;onDelete?:()=>Promise<void>};
export function WorkSessionEditor({session,onClose,onSave,onDelete}:Props){
    const[date,setDate]=useState(session?.date??toDateKey(new Date()));const[startTime,setStartTime]=useState(session?.startTime??"09:00");const[endTime,setEndTime]=useState(session?.endTime??"15:00");const[actualHours,setActualHours]=useState(session?String(session.actualMinutes/60):"0");const[notes,setNotes]=useState(session?.notes??"");const[tasks,setTasks]=useState(session?.tasksCompleted.join("\n")??"");const[completed,setCompleted]=useState(session?.completed??false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
    async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{await onSave({date,startTime,endTime,actualMinutes:Math.round(Number(actualHours)*60),notes:notes.trim(),tasksCompleted:tasks.split("\n").map((task)=>task.trim()).filter(Boolean),completed});onClose();}catch(requestError){setError(requestError instanceof Error?requestError.message:"Could not save work session");}finally{setSaving(false);}}
    async function remove(){if(!onDelete||!window.confirm("Delete this work session and its calendar event?"))return;setSaving(true);try{await onDelete();onClose();}catch(requestError){setError(requestError instanceof Error?requestError.message:"Could not delete work session");setSaving(false);}}
    return <ModalForm eyebrow="Part-Time Job" title={session?"Edit work session":"Log work hours"} onClose={onClose}><form onSubmit={submit}><div className="event-form-grid"><label><span className="field-label">Date</span><input className="text-input" type="date" value={date} onChange={(event)=>setDate(event.target.value)} required/></label><label><span className="field-label">Start</span><input className="text-input" type="time" value={startTime} onChange={(event)=>setStartTime(event.target.value)} required/></label><label><span className="field-label">End</span><input className="text-input" type="time" value={endTime} onChange={(event)=>setEndTime(event.target.value)} required/></label><label><span className="field-label">Actual hours</span><input className="text-input" type="number" min="0" max="24" step="0.25" value={actualHours} onChange={(event)=>setActualHours(event.target.value)} required/></label></div><label className="field-label">Completed tasks</label><textarea className="text-area" value={tasks} onChange={(event)=>setTasks(event.target.value)} placeholder="One task per line"/><label className="field-label">Notes</label><textarea className="text-area" value={notes} onChange={(event)=>setNotes(event.target.value)}/><label className="checkbox-field"><input type="checkbox" checked={completed} onChange={(event)=>setCompleted(event.target.checked)}/><span>Session completed</span></label>{error&&<p className="form-error">{error}</p>}<FormActions saving={saving} submitLabel="Save session" onCancel={onClose} onDelete={onDelete?remove:undefined}/></form></ModalForm>;
}
