const express=require("express");
const planner=require("../services/plannerService");
const {schemas,parse,id,date}=require("../validators/schemas");
const router=express.Router();
router.get("/events",async(req,res,next)=>{try{const start=req.query.start?parse(date,req.query.start):undefined,end=req.query.end?parse(date,req.query.end):undefined;if(start&&end&&start>end)throw Object.assign(new Error("Start date must be on or before end date"),{status:400});res.json(await planner.listEvents(req.userId,start,end));}catch(e){next(e);}});
router.post("/events",async(req,res,next)=>{try{res.status(201).json(await planner.createEvent(req.userId,parse(schemas.eventInput,req.body)));}catch(e){next(e);}});
router.put("/events/:id",async(req,res,next)=>{try{res.json(await planner.updateEvent(req.userId,parse(id,req.params.id),parse(schemas.eventInput,req.body)));}catch(e){next(e);}});
router.patch("/events/:id/completed",async(req,res,next)=>{try{res.json(await planner.setCompleted(req.userId,parse(id,req.params.id),parse(schemas.completed,req.body).completed));}catch(e){next(e);}});
router.delete("/events/:id",async(req,res,next)=>{try{await planner.deleteEvent(req.userId,parse(id,req.params.id));res.status(204).end();}catch(e){next(e);}});
module.exports={plannerRouter:router};
