import { useCallback, useEffect, useMemo, useState } from "react";
import { AnalyticsCharts } from "../components/analytics/AnalyticsCharts";
import { AnalyticsFilters } from "../components/analytics/AnalyticsFilters";
import type { RangeOption } from "../components/analytics/AnalyticsFilters";
import { apiRequest } from "../services/api";
import { subscribeRealtime } from "../hooks/useRealtime";
import { addDays, formatMinutes, startOfCalendarWeek, toDateKey } from "../utils/date";
import "./Analytics.css";

type AnalyticsData={start:string;end:string;preferences:{student:boolean;gym:boolean;partTimeJob:boolean};study:{minutes:number;completedPomodoros:number;averagePomodoroMinutes:number;bySubject:Array<{subject:string;minutes:number}>;homeworkCompleted:number;homeworkTotal:number}|null;gym:{planned:number;completed:number;missed:number;actualMinutes:number;completionRate:number}|null;job:{minutes:number;sessions:number}|null;daily:Array<{date:string;studyMinutes:number;jobMinutes:number;gymMinutes:number}>};
function range(option:RangeOption,customStart:string,customEnd:string){const now=new Date();if(option==="this-week"){const start=startOfCalendarWeek(now);return{start:toDateKey(start),end:toDateKey(addDays(start,6))};}if(option==="last-week"){const start=addDays(startOfCalendarWeek(now),-7);return{start:toDateKey(start),end:toDateKey(addDays(start,6))};}if(option==="this-month")return{start:toDateKey(new Date(now.getFullYear(),now.getMonth(),1)),end:toDateKey(new Date(now.getFullYear(),now.getMonth()+1,0))};if(option==="last-month")return{start:toDateKey(new Date(now.getFullYear(),now.getMonth()-1,1)),end:toDateKey(new Date(now.getFullYear(),now.getMonth(),0))};return customStart<=customEnd?{start:customStart,end:customEnd}:{start:customEnd,end:customStart};}
export function Analytics(){
    const[rangeOption,setRangeOption]=useState<RangeOption>("this-week");const[customStart,setCustomStart]=useState(toDateKey(startOfCalendarWeek(new Date())));const[customEnd,setCustomEnd]=useState(toDateKey(new Date()));const[data,setData]=useState<AnalyticsData|null>(null);const[error,setError]=useState("");const selected=useMemo(()=>range(rangeOption,customStart,customEnd),[customEnd,customStart,rangeOption]);
    const load=useCallback(()=>{setError("");return apiRequest<AnalyticsData>(`/api/analytics?start=${selected.start}&end=${selected.end}`).then(setData).catch((requestError)=>setError(requestError instanceof Error?requestError.message:"Could not load analytics"));},[selected.end,selected.start]);
    useEffect(()=>{void load();},[load]);
    useEffect(()=>subscribeRealtime((change)=>{if(change.scope!=="presence")void load();}),[load]);
    return <main className="analytics-page page-shell"><header className="analytics-header"><div><p className="eyebrow">Database analytics</p><h1>Analytics</h1><p>Aggregated from your authenticated records.</p></div><AnalyticsFilters rangeOption={rangeOption} customStart={customStart} customEnd={customEnd} onRangeChange={setRangeOption} onStartChange={setCustomStart} onEndChange={setCustomEnd}/></header>{error&&<div className="notice notice-error">{error}</div>}{data&&<><section className="metric-grid">{data.study&&<><div className="metric-card"><span>Study time</span><strong>{formatMinutes(data.study.minutes)}</strong></div><div className="metric-card"><span>Pomodoros</span><strong>{data.study.completedPomodoros}</strong></div><div className="metric-card"><span>Homework</span><strong>{data.study.homeworkCompleted} / {data.study.homeworkTotal}</strong></div></>}{data.gym&&<><div className="metric-card"><span>Workout completion</span><strong>{data.gym.completionRate}%</strong></div><div className="metric-card"><span>Workout time</span><strong>{formatMinutes(data.gym.actualMinutes)}</strong></div></>}{data.job&&<><div className="metric-card"><span>Part-Time Job</span><strong>{formatMinutes(data.job.minutes)}</strong></div><div className="metric-card"><span>Work sessions</span><strong>{data.job.sessions}</strong></div></>}</section><AnalyticsCharts dailyData={data.daily} studyBySubject={data.study?.bySubject||[]} preferences={data.preferences}/></>}</main>;
}
