import { useCallback, useEffect, useMemo, useState } from "react";
import { AnalyticsCharts } from "../components/analytics/AnalyticsCharts";
import { AnalyticsFilters } from "../components/analytics/AnalyticsFilters";
import type { RangeOption } from "../components/analytics/AnalyticsFilters";
import { apiRequest } from "../services/api";
import { subscribeRealtime } from "../hooks/useRealtime";
import { addDays, formatMinutes, startOfCalendarWeek, toDateKey } from "../utils/date";
import "./Analytics.css";

type AnalyticsData={start:string;end:string;preferences:{student:boolean;gym:boolean;partTimeJob:boolean};planner:{planned:number;completed:number;completionRate:number};study:{minutes:number;plannedMinutes:number;completedPomodoros:number;averagePomodoroMinutes:number;bySubject:Array<{subject:string;minutes:number}>;goals:Array<{subject:string;actualMinutes:number;targetWeeklyMinutes:number;targetMonthlyMinutes:number;weeklyProgressPercent:number;monthlyProgressPercent:number}>;homeworkCompleted:number;homeworkTotal:number}|null;gym:{planned:number;completed:number;missed:number;plannedMinutes:number;actualMinutes:number;completionRate:number}|null;job:{minutes:number;sessions:number;plannedSessions:number;completedSessions:number;plannedMinutes:number}|null;daily:Array<{date:string;studyMinutes:number;jobMinutes:number;gymMinutes:number}>};
function range(option:RangeOption,customStart:string,customEnd:string){const now=new Date();if(option==="this-week"){const start=startOfCalendarWeek(now);return{start:toDateKey(start),end:toDateKey(addDays(start,6))};}if(option==="last-week"){const start=addDays(startOfCalendarWeek(now),-7);return{start:toDateKey(start),end:toDateKey(addDays(start,6))};}if(option==="this-month")return{start:toDateKey(new Date(now.getFullYear(),now.getMonth(),1)),end:toDateKey(new Date(now.getFullYear(),now.getMonth()+1,0))};if(option==="last-month")return{start:toDateKey(new Date(now.getFullYear(),now.getMonth()-1,1)),end:toDateKey(new Date(now.getFullYear(),now.getMonth(),0))};if(option==="all-time")return{start:"2000-01-01",end:toDateKey(now)};return customStart<=customEnd?{start:customStart,end:customEnd}:{start:customEnd,end:customStart};}
export function Analytics(){
    const[rangeOption,setRangeOption]=useState<RangeOption>("this-week");const[customStart,setCustomStart]=useState(toDateKey(startOfCalendarWeek(new Date())));const[customEnd,setCustomEnd]=useState(toDateKey(new Date()));const[data,setData]=useState<AnalyticsData|null>(null);const[error,setError]=useState("");const selected=useMemo(()=>range(rangeOption,customStart,customEnd),[customEnd,customStart,rangeOption]);
    const[loading,setLoading]=useState(true);
    const load=useCallback(()=>{setError("");setLoading(true);return apiRequest<AnalyticsData>(`/api/analytics?start=${selected.start}&end=${selected.end}`).then(setData).catch((requestError)=>setError(requestError instanceof Error?requestError.message:"Could not load analytics")).finally(()=>setLoading(false));},[selected.end,selected.start]);
    useEffect(()=>{void load();},[load]);
    useEffect(()=>subscribeRealtime((change)=>{if(change.scope!=="presence")void load();}),[load]);
    return <main className="analytics-page page-shell"><header className="analytics-header"><div><p className="eyebrow">Database analytics</p><h1>Analytics</h1><p>Aggregated from your authenticated records.</p></div><AnalyticsFilters rangeOption={rangeOption} customStart={customStart} customEnd={customEnd} onRangeChange={setRangeOption} onStartChange={setCustomStart} onEndChange={setCustomEnd}/></header>{loading&&!data&&<div className="calendar-loading">Loading analytics...</div>}{error&&<div className="notice notice-error">{error}</div>}{data&&<><section className="metric-grid"><div className="metric-card"><span>Planner completion</span><strong>{data.planner.completionRate}%</strong></div>{data.study&&<><div className="metric-card"><span>Study time</span><strong>{formatMinutes(data.study.minutes)}</strong></div><div className="metric-card"><span>Pomodoros</span><strong>{data.study.completedPomodoros}</strong></div><div className="metric-card"><span>Homework</span><strong>{data.study.homeworkCompleted} / {data.study.homeworkTotal}</strong></div></>}{data.gym&&<><div className="metric-card"><span>Workout completion</span><strong>{data.gym.completionRate}%</strong></div><div className="metric-card"><span>Workout time</span><strong>{formatMinutes(data.gym.actualMinutes)}</strong></div></>}{data.job&&<><div className="metric-card"><span>Part-Time Job</span><strong>{formatMinutes(data.job.minutes)}</strong></div><div className="metric-card"><span>Work sessions</span><strong>{data.job.sessions}</strong></div></>}</section>{data.study&&<section className="analytics-goals" aria-labelledby="analytics-goals-heading"><div className="section-header"><div><p className="eyebrow">Study Goals</p><h2 id="analytics-goals-heading">Subject progress</h2></div></div>{data.study.goals.length?<div className="analytics-goal-list">{data.study.goals.map((goal)=><div className="analytics-goal-row" key={goal.subject}><div><strong>{goal.subject}</strong><span>{formatMinutes(goal.actualMinutes)} actual / {goal.targetWeeklyMinutes?`${formatMinutes(goal.targetWeeklyMinutes)} weekly target`:"No weekly target"}</span></div><strong>{goal.weeklyProgressPercent}%</strong></div>)}</div>:<p className="empty-state">Add a subject target to track Study Goal progress.</p>}</section>}{data.daily.length?<AnalyticsCharts dailyData={data.daily} studyBySubject={data.study?.bySubject||[]} preferences={data.preferences}/>:<section className="analytics-empty"><p className="empty-state">No activity was recorded for this date range.</p></section>}</>}</main>;
}
