const crypto = require("crypto");
const { getPool, withTransaction } = require("../db/pool");
const { schedule, fail } = require("../utils/domain");
const map = require("./mappers");
const planner = require("./plannerService");
const partner = require("./partnerService");

async function getData(userId) {
    const [subjects, study, homework, workouts, job, workSessions] = await Promise.all([
        getPool().query("SELECT * FROM subjects WHERE user_id=$1 ORDER BY name",[userId]),
        getPool().query("SELECT * FROM study_sessions WHERE user_id=$1 ORDER BY session_date,start_time",[userId]),
        getPool().query("SELECT * FROM homework WHERE user_id=$1 ORDER BY due_date,due_time",[userId]),
        getPool().query("SELECT * FROM scheduled_workouts WHERE user_id=$1 AND status<>'cancelled' ORDER BY workout_date,start_time",[userId]),
        getPool().query("SELECT * FROM part_time_jobs WHERE user_id=$1",[userId]),
        getPool().query("SELECT * FROM work_sessions WHERE user_id=$1 ORDER BY work_date,start_time",[userId]),
    ]);
    return { subjects: subjects.rows.map(map.subject), studySessions: study.rows.map(map.studySession), homeworkTasks: homework.rows.map(map.homework), workouts: workouts.rows.map(map.workout), partTimeJob: map.job(job.rows[0]), workSessions: workSessions.rows.map(map.workSession) };
}

async function createSubject(userId,input){const result=await getPool().query("INSERT INTO subjects(id,user_id,name,target_weekly_hours,target_monthly_hours,priority,color) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[crypto.randomUUID(),userId,input.name,input.targetWeeklyHours,input.targetMonthlyHours,input.priority,input.color]);return map.subject(result.rows[0]);}
async function updateSubject(userId,id,input){return withTransaction(async(client)=>{const result=await client.query("UPDATE subjects SET name=$3,target_weekly_hours=$4,target_monthly_hours=$5,priority=$6,color=$7,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *",[id,userId,input.name,input.targetWeeklyHours,input.targetMonthlyHours,input.priority,input.color]);if(!result.rowCount)fail("Subject not found",404);await client.query("UPDATE homework SET subject_name=$3,updated_at=NOW() WHERE subject_id=$1 AND user_id=$2",[id,userId,input.name]);await client.query("UPDATE activity_sessions SET subject=$3,updated_at=NOW() WHERE subject_id=$1 AND user_id=$2",[id,userId,input.name]);await client.query(`UPDATE calendar_events e SET title=$3,metadata=e.metadata||jsonb_build_object('subjectId',$1),updated_at=NOW() FROM study_sessions ss WHERE ss.subject_id=$1 AND ss.user_id=$2 AND ss.event_id=e.id AND e.user_id=$2`,[id,userId,input.name]);await client.query(`UPDATE calendar_events e SET metadata=e.metadata||jsonb_build_object('subjectId',$1,'subject',$3::text),updated_at=NOW() FROM homework h WHERE h.subject_id=$1 AND h.user_id=$2 AND h.event_id=e.id AND e.user_id=$2`,[id,userId,input.name]);return map.subject(result.rows[0]);});}
async function deleteSubject(userId,id){return withTransaction(async(client)=>{const linked=await client.query("SELECT 1 FROM study_sessions WHERE subject_id=$1 AND user_id=$2 LIMIT 1",[id,userId]);if(linked.rowCount)fail("Delete or reassign this subject's Study sessions first",409);const homeworkEvents=await client.query("SELECT event_id FROM homework WHERE subject_id=$1 AND user_id=$2",[id,userId]);if(homeworkEvents.rowCount)await client.query("UPDATE calendar_events SET metadata=metadata-'subjectId',updated_at=NOW() WHERE user_id=$1 AND id=ANY($2::uuid[])",[userId,homeworkEvents.rows.map((row)=>row.event_id)]);const result=await client.query("DELETE FROM subjects WHERE id=$1 AND user_id=$2",[id,userId]);if(!result.rowCount)fail("Subject not found",404);});}

async function createStudySession(userId,input){return withTransaction(async(client)=>{const subject=await client.query("SELECT * FROM subjects WHERE id=$1 AND user_id=$2",[input.subjectId,userId]);if(!subject.rowCount)fail("Choose a valid subject");const planned=schedule(input,"Study session");const id=crypto.randomUUID();const eventId=crypto.randomUUID();const completedAt=input.completed?new Date():null;await planner.insertEvent(client,userId,{title:subject.rows[0].name,type:"study",...input,metadata:{}},eventId,{entityType:"studySession",entityId:id,subjectId:input.subjectId});const result=await client.query("INSERT INTO study_sessions(id,user_id,event_id,subject_id,session_date,start_time,end_time,planned_minutes,actual_minutes,completed,completed_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[id,userId,eventId,input.subjectId,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.actualMinutes,input.completed,completedAt,input.notes]);return map.studySession(result.rows[0]);});}
async function updateStudySession(userId,id,input){return withTransaction(async(client)=>{const current=await client.query("SELECT * FROM study_sessions WHERE id=$1 AND user_id=$2 FOR UPDATE",[id,userId]);if(!current.rowCount)fail("Study session not found",404);const subject=await client.query("SELECT * FROM subjects WHERE id=$1 AND user_id=$2",[input.subjectId,userId]);if(!subject.rowCount)fail("Choose a valid subject");const planned=schedule(input,"Study session");const result=await client.query("UPDATE study_sessions SET subject_id=$3,session_date=$4,start_time=$5,end_time=$6,planned_minutes=$7,actual_minutes=$8,completed=$9,completed_at=CASE WHEN $9 THEN COALESCE(completed_at,NOW()) ELSE NULL END,notes=$10,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *",[id,userId,input.subjectId,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.actualMinutes,input.completed,input.notes]);await client.query("UPDATE calendar_events SET title=$3,event_date=$4,start_time=$5,end_time=$6,duration_minutes=$7,completed=$8,notes=$9,metadata=$10,updated_at=NOW() WHERE id=$1 AND user_id=$2",[current.rows[0].event_id,userId,subject.rows[0].name,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.completed,input.notes,{entityType:"studySession",entityId:id,subjectId:input.subjectId}]);return map.studySession(result.rows[0]);});}
async function deleteLinked(userId,table,id,label){return withTransaction(async(client)=>{const result=await client.query(`SELECT event_id FROM ${table} WHERE id=$1 AND user_id=$2`,[id,userId]);if(!result.rowCount)fail(`${label} not found`,404);await client.query("DELETE FROM calendar_events WHERE id=$1 AND user_id=$2",[result.rows[0].event_id,userId]);});}

function homeworkStartTime(input){const end=Number(input.dueTime.slice(0,2))*60+Number(input.dueTime.slice(3)),start=end-input.estimatedMinutes;if(start<0)fail("Estimated time must fit before the due time on the same day");return `${String(Math.floor(start/60)).padStart(2,"0")}:${String(start%60).padStart(2,"0")}`;}
async function createHomework(userId,input){return withTransaction(async(client)=>{const id=crypto.randomUUID(),eventId=crypto.randomUUID(),completed=input.status==="completed",startTime=homeworkStartTime(input);const subject=await client.query("SELECT id FROM subjects WHERE user_id=$1 AND LOWER(name)=LOWER($2)",[userId,input.subject]);await planner.insertEvent(client,userId,{title:input.title,type:"homework",date:input.dueDate,startTime,endTime:input.dueTime,completed,notes:input.description,metadata:{}},eventId,{entityType:"homeworkTask",entityId:id,subjectId:subject.rows[0]?.id||null,subject:input.subject,priority:input.priority});const result=await client.query("INSERT INTO homework(id,user_id,event_id,subject_id,subject_name,title,description,due_date,due_time,priority,estimated_minutes,status,completed_date,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *",[id,userId,eventId,subject.rows[0]?.id||null,input.subject,input.title,input.description,input.dueDate,input.dueTime,input.priority,input.estimatedMinutes,input.status,completed?(input.completedDate||input.dueDate):null,completed?new Date():null]);if(completed)await partner.recordSharedActivity(userId,"homework_completed","Completed a homework task.",client);return map.homework(result.rows[0]);});}
async function updateHomework(userId,id,input){return withTransaction(async(client)=>{const current=await client.query("SELECT event_id,status FROM homework WHERE id=$1 AND user_id=$2 FOR UPDATE",[id,userId]);if(!current.rowCount)fail("Homework task not found",404);const completed=input.status==="completed",startTime=homeworkStartTime(input);const subject=await client.query("SELECT id FROM subjects WHERE user_id=$1 AND LOWER(name)=LOWER($2)",[userId,input.subject]);const result=await client.query("UPDATE homework SET subject_id=$3,subject_name=$4,title=$5,description=$6,due_date=$7,due_time=$8,priority=$9,estimated_minutes=$10,status=$11::varchar,completed_date=CASE WHEN $11::varchar='completed' THEN COALESCE($12,CURRENT_DATE) ELSE NULL END,completed_at=CASE WHEN $11::varchar='completed' THEN COALESCE(completed_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *",[id,userId,subject.rows[0]?.id||null,input.subject,input.title,input.description,input.dueDate,input.dueTime,input.priority,input.estimatedMinutes,input.status,input.completedDate]);await client.query("UPDATE calendar_events SET title=$3,event_date=$4,start_time=$5,end_time=$6,duration_minutes=$7,completed=$8,notes=$9,metadata=$10,updated_at=NOW() WHERE id=$1 AND user_id=$2",[current.rows[0].event_id,userId,input.title,input.dueDate,startTime,input.dueTime,input.estimatedMinutes,completed,input.description,{entityType:"homeworkTask",entityId:id,subjectId:subject.rows[0]?.id||null,subject:input.subject,priority:input.priority}]);if(completed&&current.rows[0].status!=="completed")await partner.recordSharedActivity(userId,"homework_completed","Completed a homework task.",client);return map.homework(result.rows[0]);});}

async function upsertJob(userId,input){const result=await getPool().query("INSERT INTO part_time_jobs(id,user_id,job_name,company,hourly_target) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id) DO UPDATE SET job_name=EXCLUDED.job_name,company=EXCLUDED.company,hourly_target=EXCLUDED.hourly_target,updated_at=NOW() RETURNING *",[crypto.randomUUID(),userId,input.jobName,input.company,input.hourlyTarget??null]);return map.job(result.rows[0]);}
async function createWorkSession(userId,input){return withTransaction(async(client)=>{const job=await client.query("SELECT * FROM part_time_jobs WHERE user_id=$1",[userId]);if(!job.rowCount)fail("Configure your part-time job first",409);const planned=schedule(input,"Work session"),id=crypto.randomUUID(),eventId=crypto.randomUUID();await planner.insertEvent(client,userId,{title:job.rows[0].job_name,type:"job",...input,metadata:{}},eventId,{entityType:"workSession",entityId:id,jobId:job.rows[0].id});const result=await client.query("INSERT INTO work_sessions(id,user_id,job_id,event_id,work_date,start_time,end_time,planned_minutes,actual_minutes,completed,completed_at,notes,tasks_completed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *",[id,userId,job.rows[0].id,eventId,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.actualMinutes,input.completed,input.completed?new Date():null,input.notes,JSON.stringify(input.tasksCompleted)]);return map.workSession(result.rows[0]);});}
async function updateWorkSession(userId,id,input){return withTransaction(async(client)=>{const current=await client.query("SELECT ws.event_id,j.job_name FROM work_sessions ws JOIN part_time_jobs j ON j.id=ws.job_id AND j.user_id=ws.user_id WHERE ws.id=$1 AND ws.user_id=$2 FOR UPDATE",[id,userId]);if(!current.rowCount)fail("Work session not found",404);const planned=schedule(input,"Work session");const result=await client.query("UPDATE work_sessions SET work_date=$3,start_time=$4,end_time=$5,planned_minutes=$6,actual_minutes=$7,completed=$8,completed_at=CASE WHEN $8 THEN COALESCE(completed_at,NOW()) ELSE NULL END,notes=$9,tasks_completed=$10,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *",[id,userId,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.actualMinutes,input.completed,input.notes,JSON.stringify(input.tasksCompleted)]);await client.query("UPDATE calendar_events SET title=$3,event_date=$4,start_time=$5,end_time=$6,duration_minutes=$7,completed=$8,notes=$9,updated_at=NOW() WHERE id=$1 AND user_id=$2",[current.rows[0].event_id,userId,current.rows[0].job_name,planned.date,planned.startTime,planned.endTime,planned.plannedMinutes,input.completed,input.notes]);return map.workSession(result.rows[0]);});}

async function listTasks(userId){return (await getPool().query("SELECT * FROM tasks WHERE user_id=$1 ORDER BY completed,due_date NULLS LAST,created_at",[userId])).rows.map(map.camelizeRow);}
async function createTask(userId,input){return map.camelizeRow((await getPool().query("INSERT INTO tasks(id,user_id,title,category,completed,due_date) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[crypto.randomUUID(),userId,input.title,input.category,input.completed,input.dueDate??null])).rows[0]);}
async function updateTask(userId,id,input){const fields=[],values=[id,userId];for(const [key,column] of [["title","title"],["category","category"],["completed","completed"],["dueDate","due_date"]])if(Object.prototype.hasOwnProperty.call(input,key)){values.push(input[key]);fields.push(`${column}=$${values.length}`);}const result=await getPool().query(`UPDATE tasks SET ${fields.join(",")},updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *`,values);if(!result.rowCount)fail("Task not found",404);return map.camelizeRow(result.rows[0]);}
async function deleteTask(userId,id){const result=await getPool().query("DELETE FROM tasks WHERE id=$1 AND user_id=$2",[id,userId]);if(!result.rowCount)fail("Task not found",404);}

module.exports={getData,createSubject,updateSubject,deleteSubject,createStudySession,updateStudySession,deleteStudySession:(u,i)=>deleteLinked(u,"study_sessions",i,"Study session"),createHomework,updateHomework,deleteHomework:(u,i)=>deleteLinked(u,"homework",i,"Homework task"),upsertJob,createWorkSession,updateWorkSession,deleteWorkSession:(u,i)=>deleteLinked(u,"work_sessions",i,"Work session"),listTasks,createTask,updateTask,deleteTask};
